Project print_shop {
    database_type: 'NoSQL'
}
Table users as U {
    id int [pk, increment]
    user_name varchar
    first_name varchar
    last_name varchar
    note: "table 'users' contains user information"
}
Table merchants {
    id int [pk]
    admin_id int [ref: > U.id]
    name varchar
}
Table products {
    id int [pk]
    name varchar
    price int
    stock int
    merchant_id int [ref: > merchants.id]
}
Table reviews {
    id int [pk]
    write_up varch
    prod_id int [ref: > products.id]
}
Table checkout_items {
    cust_id int [ref: > U.id]
    prod_id int [ref: > products.id]
    quantity int
}